"""Tests for the article repository (storage layer)."""

import json
import pytest
from pathlib import Path
from unittest.mock import patch
from src.data.repository import save_article, _format_markdown


class TestSaveArticle:
    """Tests for save_article()."""

    def test_creates_all_three_files(self, tmp_path, sample_content):
        with patch("src.data.repository.ARTICLES_DIR", str(tmp_path / "articles")), \
             patch("src.data.repository.METADATA_DIR", str(tmp_path / "metadata")):
            result = save_article("trex", sample_content)

            assert Path(result["json"]).exists()
            assert Path(result["markdown"]).exists()
            assert Path(result["metadata"]).exists()

    def test_json_file_contains_content(self, tmp_path, sample_content):
        with patch("src.data.repository.ARTICLES_DIR", str(tmp_path / "articles")), \
             patch("src.data.repository.METADATA_DIR", str(tmp_path / "metadata")):
            result = save_article("trex", sample_content)

            with open(result["json"]) as f:
                data = json.load(f)
            assert data["article"] == sample_content["article"]
            assert data["social_snippet"] == sample_content["social_snippet"]

    def test_metadata_file_has_tracking_fields(self, tmp_path, sample_content):
        with patch("src.data.repository.ARTICLES_DIR", str(tmp_path / "articles")), \
             patch("src.data.repository.METADATA_DIR", str(tmp_path / "metadata")):
            result = save_article("trex", sample_content)

            with open(result["metadata"]) as f:
                meta = json.load(f)
            assert meta["dinosaur_id"] == "trex"
            assert "generated_at" in meta
            assert meta["article_length"] == len(sample_content["article"])
            assert meta["hashtag_count"] == len(sample_content["hashtags"])

    def test_markdown_file_contains_article(self, tmp_path, sample_content):
        with patch("src.data.repository.ARTICLES_DIR", str(tmp_path / "articles")), \
             patch("src.data.repository.METADATA_DIR", str(tmp_path / "metadata")):
            result = save_article("trex", sample_content)

            text = Path(result["markdown"]).read_text()
            assert "Trex" in text  # title derived from id
            assert sample_content["social_snippet"] in text


class TestFormatMarkdown:
    """Tests for _format_markdown()."""

    def test_includes_sections(self, sample_content):
        md = _format_markdown("trex", sample_content)
        assert "# Trex" in md
        assert "## Article" in md
        assert "## Social Snippet" in md
        assert "## Hashtags" in md
        assert "Generated by Dinopedia" in md

    def test_includes_hashtags(self, sample_content):
        md = _format_markdown("trex", sample_content)
        for tag in sample_content["hashtags"]:
            assert tag in md

    def test_underscores_replaced_in_title(self, sample_content):
        md = _format_markdown("test_dino_name", sample_content)
        assert "# Test Dino Name" in md
