"""Repository for saving generated content."""

from datetime import datetime
from src.utils.file_io import save_json, save_text
from src.logger import get_logger

logger = get_logger(__name__)

OUTPUT_DIR = "output"
ARTICLES_DIR = f"{OUTPUT_DIR}/articles"
METADATA_DIR = f"{OUTPUT_DIR}/metadata"

def save_article(dinosaur_id, content):
    """
    Save generated article to output/ directory.
    
    Args:
        dinosaur_id: ID of dinosaur
        content: dict with article, social_snippet, hashtags
        
    Returns:
        dict with paths to saved files
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{dinosaur_id}_{timestamp}"
    
    # Save article JSON (full content)
    json_path = f"{ARTICLES_DIR}/{filename}.json"
    save_json(content, json_path)
    
    # Save article markdown (readable format)
    markdown_path = f"{ARTICLES_DIR}/{filename}.md"
    markdown = _format_markdown(dinosaur_id, content)
    save_text(markdown, markdown_path)
    
    # Save metadata (tracking)
    metadata = {
        "dinosaur_id": dinosaur_id,
        "generated_at": datetime.now().isoformat(),
        "article_file": json_path,
        "markdown_file": markdown_path,
        "article_length": len(content["article"]),
        "hashtag_count": len(content["hashtags"])
    }
    metadata_path = f"{METADATA_DIR}/{filename}.json"
    save_json(metadata, metadata_path)
    
    logger.info(f"Saved article for {dinosaur_id}: {json_path}")
    
    return {
        "json": json_path,
        "markdown": markdown_path,
        "metadata": metadata_path
    }

def _format_markdown(dinosaur_id, content):
    """Format content as markdown."""
    return f"""# {dinosaur_id.replace('_', ' ').title()}

## Article

{content['article']}

## Social Snippet

{content['social_snippet']}

## Hashtags

{' '.join(content['hashtags'])}

---

*Generated by Dinopedia*
"""
